name: pubtator-test
dependencies:
- python==3.6.0
- lxml==4.4.2
- tqdm==4.41.1
- pandas==0.25.3
- pip==19.3.1
- pip:
    - git+https://github.com/en-dash/PyBioC@a21bd181ce3b89de791db4bb7db6ca1c48167648
